global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
- job_name: actix-monitoring
  authorization:
    type: "bearer"
    credentials: "bearer_token"
  honor_labels: true
  static_configs:
  - targets: ['host.docker.internal:4000']